# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: zip up war file
      run: tar -cvf deploy.tar webapp/target/webapp.war

    - name: Copy file via ssh 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.MAIN_ANS_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "deploy.tar"
        target: "github/"
        name: Build
        
    - name: Perform image creation, docker hub push, creating kubernetes deployment&service 
            with updated app pulled from docker hub
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.MAIN_ANS_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd github/
          rm -rf webapp/
          tar -xf deploy.tar
          sudo cp /home/ec2-user/github/webapp/target/webapp.war /opt/docker
          cd /opt/docker
          ansible-playbook -i hosts -u ec2-user create_image_regapp.yml
          sudo service docker start
          ansible-playbook -i hosts -u ec2-user kube_service_and_deploy.yml