# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: |
        cd ~
        ls -la
        pwd
        sudo mkdir rsync
        sudo chmod 777 /home/runner/rsync
        sudo mv /home/runner/work/regapp/regapp/webapp/target/webapp.war ~/rsync
    - run: |
        cd /home
        ls -la
        pwd
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
    - run: |
        cd /home
        ls -la
        pwd   
    - name: Deploy with rsync
      run: sudo rsync -avz -e ~/rsync ${{ secrets.MAIN_ANS_USER }}@${{ secrets.SSH_HOST }}:/opt/docker  
      
  build2:
    name: test
    uses: ./.github/workflows/deploy_template.yml
    with:
      environment: 'ans'
    secrets: inherit
    
  build3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
      
    - name: Deploy with rsync
      run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" /home/runner/work/regapp/regapp/webapp/target/ ${{ secrets.MAIN_ANS_USER }}@${{ secrets.SSH_HOST }}:/opt/docker












#    - name: test
#      run: 'echo "$SSH_KEY" | base64'
#      shell: bash
#      env:
#        SSH_KEY: ${{ secrets.EC2USER }}
#    - name: test    
#      run: 'echo "Cg==" | base64 -d'
#      shell: bash
#    - name: Install SSH Key
#      uses: shimataro/ssh-key-action@v2
#      with:
#        key: ${{ secrets.GH_PRIVATE_KEY_TWO }}
#    - name: Adding Known Hosts
#      run: ssh-keyscan -H ${{ secrets.SSH_KNOWN_HOSTS }} >> ~/.ssh/known_hosts
